//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerceTicket2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SkytourEntities2 : DbContext
    {
        public SkytourEntities2()
            : base("name=SkytourEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Airline> Airline { get; set; }
        public virtual DbSet<AirlineTopupBalance> AirlineTopupBalance { get; set; }
        public virtual DbSet<Airport> Airport { get; set; }
        public virtual DbSet<DomesticRoute> DomesticRoute { get; set; }
        public virtual DbSet<OrderFlight> OrderFlight { get; set; }
    }
}
